### ISSUE TITLE
negativan broj linije

### ISSUE THREAD

**Issue by karlosintic** [whiteShtef/kadmiide#1]
prima ti i negativan broj linije
![ss 2016-06-03 at 08 00 03](https://cloud.githubusercontent.com/assets/6306855/15788048/d23cec3c-29c5-11e6-82f7-7a873164557d.png)

**Comment by whiteShtef** [comment]
Hvala na primjedbi!
Rješeno.
`#"linija" integer sanitizazion;
#bug notified by @karlosintic;
linija=abs(linija);`
